# Generated by Django 6.0.1 on 2026-06-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='catogery',
            new_name='category',
        ),
    ]
